# Generated by Django 4.2.2 on 2024-02-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='process',
            table='processes',
        ),
    ]
