# Generated by Django 4.2.2 on 2024-03-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutiestrouble',
            name='snippet_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='snippets.snippet', verbose_name='スニペットid'),
            preserve_default=False,
        ),
    ]
