# Generated by Django 4.2.2 on 2024-02-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duties_trouble',
            name='snippet_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='snippets.snippet'),
        ),
    ]
