# Generated by Django 4.2.2 on 2024-02-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='weather',
            field=models.CharField(max_length=5, verbose_name='天気'),
        ),
    ]
