# Generated by Django 4.2.2 on 2024-02-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='duties_id',
            new_name='duties_trouble_id',
        ),
        migrations.AddField(
            model_name='snippet',
            name='car_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='snippets.car', verbose_name='アカウントid'),
        ),
    ]
