# Generated by Django 4.2.2 on 2024-02-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_duties_trouble_snippet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duties_trouble',
            name='snippet_id',
        ),
        migrations.AddField(
            model_name='snippet',
            name='duties_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='snippets.duties_trouble'),
        ),
        migrations.AlterField(
            model_name='duties_trouble',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='トラブルid'),
        ),
    ]
