# Generated by Django 4.2.2 on 2024-02-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='end_mileage',
            field=models.IntegerField(verbose_name='到着時メーター'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='end_time',
            field=models.TimeField(max_length=10, verbose_name='終業時間'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='日報ID'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='start_mileage',
            field=models.IntegerField(verbose_name='出発時メーター'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='start_time',
            field=models.TimeField(max_length=10, verbose_name='始業時間'),
        ),
    ]
