# Generated by Django 4.2.2 on 2024-02-23 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_duties_id_snippet_duties_trouble_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='free_space',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='備考欄'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='car_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='snippets.car', verbose_name='車両id'),
        ),
    ]
