# Generated by Django 4.2.2 on 2024-02-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='アカウントID'),
        ),
    ]
