# Generated by Django 4.2.2 on 2024-02-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(editable=False, max_length=6, primary_key=True, serialize=False, verbose_name='車両ID')),
                ('vehicle_number', models.CharField(max_length=15, verbose_name='車両番号')),
                ('now_mileage', models.IntegerField(max_length=25, verbose_name='走行距離')),
            ],
            options={
                'verbose_name': '車両',
                'db_table': 'car',
            },
        ),
    ]
