# Generated by Django 4.2.2 on 2024-02-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tire_damage', models.BooleanField(blank=True, default=False, verbose_name='タイヤの損傷(空気圧/摩耗/亀裂/損傷)')),
                ('is_tire_groove', models.BooleanField(blank=True, default=False, verbose_name='タイヤの溝の深さ')),
                ('is_tire_parts', models.BooleanField(blank=True, default=False, verbose_name='タイヤのナット・ボルト(緩み/脱落)')),
                ('is_radiator', models.BooleanField(blank=True, default=False, verbose_name='ラジエータの冷却水(液量)')),
                ('is_brake_oil', models.BooleanField(blank=True, default=False, verbose_name='ブレーキオイル(液量)')),
                ('is_air_tank', models.BooleanField(blank=True, default=False, verbose_name='エアタンク(凝水)')),
                ('is_air_brake', models.BooleanField(blank=True, default=False, verbose_name='エアブレーキ(空気圧/排気音)')),
                ('is_brake_pedal', models.BooleanField(blank=True, default=False, verbose_name='ブレーキペダルの踏みしろ')),
                ('is_parking_brake', models.BooleanField(blank=True, default=False, verbose_name='駐車ブレーキ(かかり具合/引きしろ)')),
                ('is_engine_oil', models.BooleanField(blank=True, default=False, verbose_name='エンジンオイル(液量)')),
                ('is_battery', models.BooleanField(blank=True, default=False, verbose_name='バッテリー(液量)')),
                ('is_belt', models.BooleanField(blank=True, default=False, verbose_name='ファン・ベルトの異常(張り/損傷)')),
                ('is_washer_fluid', models.BooleanField(blank=True, default=False, verbose_name='ウォッシャー液/ワイパー(液量/噴射状態/払拭状態)')),
                ('is_engine', models.BooleanField(blank=True, default=False, verbose_name='エンジン(かかり具合/異音/状態)')),
                ('is_light', models.BooleanField(blank=True, default=False, verbose_name='ライト(ヘッドライト/ウインカー/車内灯/ハザード/速度表示)')),
                ('is_brake_details', models.BooleanField(blank=True, default=False, verbose_name='ブレーキチャンバロッド/ブレーキペダルのライニング')),
                ('is_before_trouble', models.BooleanField(default=False, verbose_name='前日の異常')),
                ('is_today_trouble', models.BooleanField(default=False, verbose_name='本日の異常')),
            ],
            options={
                'verbose_name': '点検項目',
                'db_table': 'checklist',
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='車両ID'),
        ),
        migrations.AlterField(
            model_name='car',
            name='now_mileage',
            field=models.IntegerField(verbose_name='走行距離'),
        ),
    ]
