# Generated by Django 4.2.2 on 2024-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_checklist_alter_car_id_alter_car_now_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='日報ID')),
                ('end_mileage', models.IntegerField(verbose_name='到着時メーター')),
                ('start_time', models.TimeField(blank=True, max_length=10, null=True, verbose_name='始業時間')),
                ('end_time', models.TimeField(blank=True, max_length=10, null=True, verbose_name='終業時間')),
                ('start_point', models.IntegerField(verbose_name='出発地点')),
                ('end_point', models.IntegerField(verbose_name='最終到着地点')),
                ('break_spot', models.IntegerField(verbose_name='休憩地点')),
                ('weather', models.CharField(blank=True, max_length=5, null=True, verbose_name='天気')),
                ('oil', models.FloatField(blank=True, max_length=4, null=True, verbose_name='オイル')),
                ('gasoline_amount', models.FloatField(blank=True, max_length=4, null=True, verbose_name='給油')),
                ('is_trouble_situation', models.BooleanField(blank=True, default=False, verbose_name='事故/遅延等異常_状況')),
                ('is_trouble_cause', models.BooleanField(blank=True, default=False, verbose_name='事故/遅延等異常_原因')),
                ('is_trouble_support', models.BooleanField(blank=True, default=False, verbose_name='事故/遅延等異常_処置')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '日報',
                'db_table': 'snippets',
            },
        ),
    ]
