# Generated by Django 4.2.2 on 2024-02-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='break_spot',
            field=models.CharField(max_length=10, verbose_name='休憩地点'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='end_point',
            field=models.CharField(max_length=10, verbose_name='最終到着地点'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='start_point',
            field=models.CharField(max_length=10, verbose_name='出発地点'),
        ),
    ]
